### ISSUE TITLE
RemoveImport works, but AddImport does not

### ISSUE THREAD

**Issue by Guseyn** [openrewrite/rewrite-docs#14]
When I do smth like this:
```java
RemoveImport rmi = new RemoveImport();
rmi.setType("org.slf4j.MarkerFactory");

Collection<Change> changes = new Refactor().visit(rmi).fix(cus);
```

it works, but when I do:

```java
AddImport adi = new AddImport();
adi.setType("org.slf4j.MarkerFactory");
Collection<Change> changes = new Refactor().visit(adi).fix(cus);
```

it does get any changes

**Comment by sambsnyd** [comment]
As I believe we have now discussed in other github issues/slack, it's probably because `AddImport.onlyIfReferenced()` was not set to `true` and there was no usage of `org.slf4j.MarkerFactory` in the class. By default `AddImport` wont add an import for a type that isn't used. Since we had those discussions I've tried to clarify this in the docs page for `AddImport`.

Let me know if you think the updated documentation for `AddImport` is unclear about this.
