### ISSUE TITLE
Document what is a Quark

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-docs#168]
In response to this question and answer:
https://stackoverflow.com/a/76287210/53444

**Comment by mike-solomon** [comment]
Here's a blurb of how I'd summarize a `Quark`: 

A `Quark` in OpenRewrite serves as a representation of a file that cannot be parsed, either due to its large size or because it is a type we don't have a parser for (such as images or HTML files). Instead of disregarding such files, we capture their path and relevant metadata (but **not** the contents of these files). This allows you to move or delete these files in recipes.

I feel like we should potentially include more information, though. Things like:
* Are there any common situations where someone would stumble upon a Quark?
* Is there any advice we'd give people for working with or managing Quarks?
* What about troubleshooting? Any steps they should take?

Asked about this in the OpenRewrite channel here: https://moderneinc.slack.com/archives/C01VADFPJQZ/p1686242165918769

Once I get those answers, I can finish up a doc to resolve this issue.

**Comment by mike-solomon** [comment]
From Slack, it sounds like there are no common situations where someone would stumble across these or work with them so perhaps that paragraph is enough 🤷‍♂️
